### ISSUE TITLE
[BUG] JPKeboard::Openにデフォルト文字を指定した際にクラッシュする

### ISSUE THREAD

**Issue by kani537** [kani537/ideaCTRPF#33]
selectedIndex,_canAbort,レイアウトが変更されてしまう

**Comment by hide0123** [comment]
[メモ]
ヒープとスタックを確保しても改善されていないため、今のところ原因不明。

[参考画像]
![image](https://user-images.githubusercontent.com/48782538/218504146-e3bdc827-59cc-40e4-b5a3-8ed36c9b3565.png)

**Comment by hide0123** [comment]
[追記]

- キーボードボタン経由でメニューを開くと高い確率でクラッシュ
- JPKeyboardのインスタンスをヒープに置くと部分的に解消される
- 内部的には`_free_r`でクラッシュ（無効なポインタがdeleteされている...？）
